version = 0.1

[default.deploy.parameters]
stack_name = "urlShorter2"
resolve_s3 = true
s3_prefix = "urlShorter2"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
